### ISSUE TITLE
Extra Widget Areas

### ISSUE THREAD

**Issue by travisward** [AgriLife/agrilife-extension-unit#1]
There are two widget areas that do not apply in the "Extension Unit" version of the theme. Programs and Solutions should not be widget areas in the unit-level theme.

**Comment by ZachWatkins** [comment]
I've addressed the issue in the latest commit. You may want to check it out on http://agrilife.staging.wpengine.com/winegrapes/ before updating the production server(s).

**Comment by travisward** [comment]
Looks good
